const GOLD_IDS = [1, 21, 15, 4];

const CARDS_DATA = [
  { id: 1, isGold: true, title: "BLACK BILLIONAIRE", description: "I am grateful that I have gone through the process of becoming a billionaire, and I am worth one billion today. I am grateful that money flows to me freely and there is plenty everywhere. I am grateful that I am enjoying being a billionaire.", image: "" },
  { id: 2, isGold: false, title: "100K BY SEPTEMBER", description: "I am grateful that I hit 100K by the time September comes and we meet again. I am grateful that my hustle is paying off exactly on schedule. I am grateful that I am enjoying watching my money grow.", image: "" },
  { id: 3, isGold: false, title: "NICE LOAFERS", description: "I am grateful that I own the nicest loafers, the kind that make people look twice. I am grateful that looking sharp comes easily to me now. I am grateful that I am enjoying stepping out in style.", image: "" },
  { id: 4, isGold: true, title: "PORSCHE MACAN", description: "I am grateful that I am driving my Porsche Macan, exactly the one I pictured. I am grateful that abundance shows up in the details, down to the car in my driveway. I am grateful that I am enjoying every drive.", image: "" },
  { id: 5, isGold: false, title: "CEO ON STAGE", description: "I am grateful that I am speaking at an event as the CEO of Notify, sharing everything we've built. I am grateful that my voice and my work carry weight in rooms that matter. I am grateful that I am enjoying being seen as a leader.", image: "" },
  { id: 6, isGold: false, title: "AI STAGE", description: "I am grateful that I am speaking at an event on AI, teaching what I know to people who need it. I am grateful that my knowledge is valuable and worth sharing. I am grateful that I am enjoying being the expert in the room.", image: "" },
  { id: 7, isGold: false, title: "ZANZIBAR", description: "I am grateful that I am in Zanzibar with my beautiful girl, sun on our skin and nothing to rush for. I am grateful that we get to travel and make memories like this together. I am grateful that I am enjoying every second of it with her.", image: "" },
  { id: 8, isGold: false, title: "FOR MUM AND DAD", description: "I am grateful that I am able to gift my mum and dad, giving back even a fraction of what they gave me. I am grateful that my success reaches the people who raised me. I am grateful that I am enjoying watching their faces when I do.", image: "" },
  { id: 9, isGold: false, title: "AMAZING BODY", description: "I am grateful that I have an amazing body, strong and healthy and mine. I am grateful that discipline in the gym has become second nature. I am grateful that I am enjoying how I look and feel.", image: "" },
  { id: 10, isGold: false, title: "GOLD WATCH", description: "I am grateful that I own a gold watch with a jungle green interior, exactly how I imagined it. I am grateful that the details of my success are this specific and this beautiful. I am grateful that I am enjoying wearing it every day.", image: "" },
  { id: 11, isGold: false, title: "DATES WITH MY GIRL", description: "I am grateful that I get to keep going on dates with my girl, making the ordinary days feel special. I am grateful that our relationship keeps growing alongside everything else I'm building. I am grateful that I am enjoying every date, big or small.", image: "" },
  { id: 12, isGold: false, title: "A WIG FOR GLORIA", description: "I am grateful that I get to buy Gloria a nice wig, just because I can and because she deserves it. I am grateful that I get to spoil the people I love. I am grateful that I am enjoying being able to give like this.", image: "" },
  { id: 13, isGold: false, title: "A GREAT MENTOR", description: "I am grateful that I have met a mentor through my CEO journey, someone whose wisdom sharpens mine. I am grateful that the right people show up at the right time to guide me. I am grateful that I am enjoying learning from someone I deeply respect.", image: "" },
  { id: 14, isGold: false, title: "ME AND MY BROS WINNING", description: "I am grateful that my bros and I are all succeeding together, none of us left behind. I am grateful that the people I came up with are rising alongside me. I am grateful that I am enjoying watching all of us win.", image: "" },
  { id: 15, isGold: true, title: "SEKANI GOES VIRAL", description: "I am grateful that Sekani has launched and gone viral, recognized far beyond what I imagined. I am grateful that the work I poured myself into is changing lives at scale. I am grateful that I am enjoying watching Sekani take off.", image: "" },
  { id: 16, isGold: false, title: "JUST US, PLAYFUL", description: "I am grateful for the fun, playful, cheeky side of life with my girl, where we don't take ourselves too seriously. I am grateful that she gets to spoil me in her own way. I am grateful that I am enjoying every bit of us.", image: "" },
  { id: 17, isGold: false, title: "PENTHOUSE GETAWAY", description: "I am grateful that I have a penthouse getaway to escape to whenever I need space and quiet. I am grateful that rest looks luxurious and easy now. I am grateful that I am enjoying my own peace up there.", image: "" },
  { id: 18, isGold: false, title: "SAMBURU & OLOLOKWE", description: "I am grateful that I made it to Samburu and up Ololokwe mountain, driving that road with my girl beside me. I am grateful that adventure and nature are part of my story too. I am grateful that I am enjoying the memories we made there.", image: "" },
  { id: 19, isGold: false, title: "HAVING FUN", description: "I am grateful that I make time to simply have fun, without needing a reason. I am grateful that joy is a normal part of my everyday life, not something I have to earn. I am grateful that I am enjoying life exactly as it is.", image: "" },
  { id: 20, isGold: false, title: "ALWAYS EATING", description: "I am grateful that I get to eat all the damn time and never worry about it. I am grateful that abundance shows up on my plate and everywhere else in my life. I am grateful that I am enjoying every meal.", image: "" },
  { id: 21, isGold: true, title: "THE LEGACY", description: "I am grateful that Notify AI has transformed education across Africa, opening doors for the next generation. I am grateful that my work outlives me in the students and schools it touches. I am grateful that I am enjoying building something that matters.", image: "" }
];
